default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  development:
  adapter: postgresql
  database: prod_alpha
  host: localhost
  username: postgres
  password:

test:
  <<: *default
  database: prod_alpha_test
